export default function Middle() {
    return (
        <div className="w-[50%] h-full bg-green-500 border-r-[1px] border-gray-700">
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
            hello
        </div>
    )
}